### ISSUE TITLE
Leg Eater unable to fix charms during Area Blitz

### ISSUE THREAD

**Issue by Eddiemate** [flibber-hk/HollowKnight.RandoPlus#1]
So I was doing a randomiser using the area blitz feature, and I wanted to go fix my Fragile Strength before Radiance. However Leg Eater only sold Nothing (which I bought) since Fungal Wastes wasn't in my randomised areas, and refused to fix my charm. As far as I remember, they're perfectly repairable otherwise.

https://user-images.githubusercontent.com/77180191/154240782-1eb65b09-8882-4e4b-a46c-a92bda3d3639.mp4

**Comment by flibber-hk** [comment]
Oh, thanks for the report!

**Comment by flibber-hk** [comment]
Closed by 5f3817103eb6a2475009a30a268dd876fc25f3b4
