### ISSUE TITLE
ghost NPC locations

### ISSUE THREAD

**Issue by reduci4** [flibber-hk/HollowKnight.RandoPlus#5]
Is it possible to add the ghost NPC locations (dreamnail them to get the item) and some one-essence items to the pool? Just a meme for fun though.

**Comment by flibber-hk** [comment]
It's possible. It's not particularly high on my priority list right now (sorry), but I'd be open to accepting a pull request if someone wanted to implement it (or they could make a separate connection mod to control ghost NPC rando).

There's an alternative proposed implementation of ghost NPC rando, where the ghost locations are randomized (e.g. you enter the room that would usually have dreamshield and instead Caelif and Fera (the QG ghosts) are there. That would be a bit more work, but possibly more fun. 

Sorry if that wasn't the answer you were hoping for :/

**Comment by flibber-hk** [comment]
Implemented in #6
